// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2PScraper.DataAccess;

#nullable disable

namespace P2PScraper.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20240210214717_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("P2PScraper.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BotChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBotEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("P2PUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
